# Usar uma imagem base oficial do Python
FROM python:3.12

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos de dependências
COPY requirements-docker.txt .

# Instalar as dependências
RUN pip install --no-cache-dir -r requirements-docker.txt

# Copiar o código da aplicação
COPY . .

# Expôr a porta que a aplicação usa
EXPOSE 8000

# Comando para rodar a aplicação
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]